{% set name = "xpdConf" %}
{% set version = "0.2.1" %}
{% set sha256 = "8d8e5199a2c91081484f200be458641fd42c38fc3f5cdea4200e2410d3149ca3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - databroker
    - pyyaml

test:
  imports:
    - xpdconf

about:
  home: http://github.com/xpdAcq/xpdConf
  license: BSD-3-Clause 
  license_family: BSD
  license_file: LICENSE
  summary: 'Configuration for XPD beamlines'

extra:
  recipe-maintainers:
    - CJ-Wright
    - chiahaoliu
    - sbillinge
